name:                liberation
version:             0.1.0.0
github:              "Innf107/liberation"
license:             BSD3
author:              "Finn Schneider"
maintainer:          "finn@famschneider.info"
copyright:           "2021 Finn Schneider"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Innf107/liberation#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell

library:
  source-dirs: src

tests:
  liberation-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - liberation

benchmarks:
  liberation-bench:
    main:               Main.hs
    source-dirs:        benchmark
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
      - -fspecialize
    dependencies:
      - liberation
      - criterion
      - mtl
      - polysemy

